### ISSUE TITLE
Browsers Support

### ISSUE THREAD

**Issue by JUEsoft** [yhoungdev/code4mom.js#4]
Code4Mom.js is probably written in Es6/Es7.js and not all browsers Support Es6.js..
So, I think you should have a script to check browsers support.
Eg:
If the browser isn't supported, show a console warning showing that it's an old browser, then another condition to check if babel.js is linked, show a warning like "babel.js required to run Code4Mom.js on old browsers" if not linked.

**Comment by yhoungdev** [comment]
Wow thanks bro am gonna check that
